#
# This file is auto-generated. DO NOT EDIT
# Generated by: autospec.py
#
%define keepstatic 1
Name     : tkimg
Version  : 534
Release  : 3
URL      : file:///insilications/apps/tkimg-v534.tar.gz
Source0  : file:///insilications/apps/tkimg-v534.tar.gz
Summary  : Loads and saves PNG files
Group    : Development/Tools
License  : LGPL-2.0+ MIT
Requires: tkimg-lib = %{version}-%{release}
Requires: tkimg-man = %{version}-%{release}
BuildRequires : buildreq-cmake
BuildRequires : buildreq-configure
BuildRequires : buildreq-scons
BuildRequires : critcl
BuildRequires : critcl-dev
BuildRequires : freeglut-dev
BuildRequires : gcc-dev
BuildRequires : glibc-dev
BuildRequires : glibc-staticdev
BuildRequires : glu-dev
BuildRequires : libXScrnSaver-dev
BuildRequires : libXft
BuildRequires : libffi-dev
BuildRequires : libffi-staticdev
BuildRequires : libstdc++
BuildRequires : libstdc++-dev
BuildRequires : libxml2-dev
BuildRequires : libxml2-staticdev
BuildRequires : mesa-dev
BuildRequires : pkgconfig(quazip)
BuildRequires : pkgconfig(tcl)
BuildRequires : pkgconfig(tk)
BuildRequires : pkgconfig(x11)
BuildRequires : pkgconfig(xext)
BuildRequires : pkgconfig(xft)
BuildRequires : pkgconfig(zlib)
BuildRequires : pulseaudio
BuildRequires : pulseaudio-dev
BuildRequires : python3-dev
BuildRequires : python3-staticdev
BuildRequires : tcl
BuildRequires : tcl-dev
BuildRequires : tcl-staticdev
BuildRequires : tcllib
BuildRequires : tcllib-dev
BuildRequires : tk
BuildRequires : tk-dev
BuildRequires : tk-staticdev
BuildRequires : xz-dev
BuildRequires : xz-staticdev
BuildRequires : zlib-dev
BuildRequires : zlib-staticdev
# Suppress stripping binaries
%define __strip /bin/true
%define debug_package %{nil}

%description
Tcl/Tk Image formats (TkImg)
(Version 1.4.13 / January 2021)
Jan Nijtmans, Andreas Kupries, Paul Obermeier

%package dev
Summary: dev components for the tkimg package.
Group: Development
Requires: tkimg-lib = %{version}-%{release}
Provides: tkimg-devel = %{version}-%{release}
Requires: tkimg = %{version}-%{release}

%description dev
dev components for the tkimg package.


%package lib
Summary: lib components for the tkimg package.
Group: Libraries

%description lib
lib components for the tkimg package.


%package man
Summary: man components for the tkimg package.
Group: Default

%description man
man components for the tkimg package.


%package staticdev
Summary: staticdev components for the tkimg package.
Group: Default
Requires: tkimg-dev = %{version}-%{release}

%description staticdev
staticdev components for the tkimg package.


%prep
%setup -q -n tkimg-v534
cd %{_builddir}/tkimg-v534

%build
unset http_proxy
unset https_proxy
unset no_proxy
export SSL_CERT_FILE=/var/cache/ca-certs/anchors/ca-certificates.crt
export LANG=C.UTF-8
export SOURCE_DATE_EPOCH=1610089201
export GCC_IGNORE_WERROR=1
## altflags1 content
export CFLAGS="-O3 -march=native -mtune=native -fgraphite-identity -Wall -Wl,--as-needed -Wl,--build-id=sha1 -Wl,--enable-new-dtags -Wl,--hash-style=gnu -Wl,-O2 -Wl,-z,now -Wl,-z,relro -falign-functions=32 -flimit-function-alignment -fasynchronous-unwind-tables -fdevirtualize-at-ltrans -floop-nest-optimize -fno-math-errno -fno-semantic-interposition -fno-stack-protector -fno-trapping-math -ftree-loop-distribute-patterns -ftree-loop-vectorize -ftree-vectorize -funroll-loops -fuse-ld=bfd -fuse-linker-plugin -malign-data=cacheline -feliminate-unused-debug-types -fipa-pta -flto=16 -fno-plt -mtls-dialect=gnu2 -Wl,-sort-common -Wno-error -Wp,-D_REENTRANT -pipe -ffat-lto-objects -fPIC -fno-exceptions -pthread -static-libstdc++ -static-libgcc"
#
export CXXFLAGS="-O3 -march=native -mtune=native -fgraphite-identity -Wall -Wl,--as-needed -Wl,--build-id=sha1 -Wl,--enable-new-dtags -Wl,--hash-style=gnu -Wl,-O2 -Wl,-z,now -Wl,-z,relro -falign-functions=32 -flimit-function-alignment -fasynchronous-unwind-tables -fdevirtualize-at-ltrans -floop-nest-optimize -fno-math-errno -fno-semantic-interposition -fno-stack-protector -fno-trapping-math -ftree-loop-distribute-patterns -ftree-loop-vectorize -ftree-vectorize -funroll-loops -fuse-ld=bfd -fuse-linker-plugin -malign-data=cacheline -feliminate-unused-debug-types -fipa-pta -flto=16 -fno-plt -mtls-dialect=gnu2 -Wl,-sort-common -Wno-error -Wp,-D_REENTRANT -fvisibility-inlines-hidden -pipe -ffat-lto-objects -fPIC -fno-exceptions -pthread -static-libstdc++ -static-libgcc"
#
export FCFLAGS="-O3 -march=native -mtune=native -fgraphite-identity -Wall -Wl,--as-needed -Wl,--build-id=sha1 -Wl,--enable-new-dtags -Wl,--hash-style=gnu -Wl,-O2 -Wl,-z,now -Wl,-z,relro -falign-functions=32 -flimit-function-alignment -fasynchronous-unwind-tables -fdevirtualize-at-ltrans -floop-nest-optimize -fno-math-errno -fno-semantic-interposition -fno-stack-protector -fno-trapping-math -ftree-loop-distribute-patterns -ftree-loop-vectorize -ftree-vectorize -funroll-loops -fuse-ld=bfd -fuse-linker-plugin -malign-data=cacheline -feliminate-unused-debug-types -fipa-pta -flto=16 -fno-plt -mtls-dialect=gnu2 -Wl,-sort-common -Wno-error -Wp,-D_REENTRANT -pipe -ffat-lto-objects -fPIC -fno-exceptions -pthread -static-libstdc++ -static-libgcc"
export FFLAGS="-O3 -march=native -mtune=native -fgraphite-identity -Wall -Wl,--as-needed -Wl,--build-id=sha1 -Wl,--enable-new-dtags -Wl,--hash-style=gnu -Wl,-O2 -Wl,-z,now -Wl,-z,relro -falign-functions=32 -flimit-function-alignment -fasynchronous-unwind-tables -fdevirtualize-at-ltrans -floop-nest-optimize -fno-math-errno -fno-semantic-interposition -fno-stack-protector -fno-trapping-math -ftree-loop-distribute-patterns -ftree-loop-vectorize -ftree-vectorize -funroll-loops -fuse-ld=bfd -fuse-linker-plugin -malign-data=cacheline -feliminate-unused-debug-types -fipa-pta -flto=16 -fno-plt -mtls-dialect=gnu2 -Wl,-sort-common -Wno-error -Wp,-D_REENTRANT -pipe -ffat-lto-objects -fPIC -fno-exceptions -pthread -static-libstdc++ -static-libgcc"
export CFFLAGS="-O3 -march=native -mtune=native -fgraphite-identity -Wall -Wl,--as-needed -Wl,--build-id=sha1 -Wl,--enable-new-dtags -Wl,--hash-style=gnu -Wl,-O2 -Wl,-z,now -Wl,-z,relro -falign-functions=32 -flimit-function-alignment -fasynchronous-unwind-tables -fdevirtualize-at-ltrans -floop-nest-optimize -fno-math-errno -fno-semantic-interposition -fno-stack-protector -fno-trapping-math -ftree-loop-distribute-patterns -ftree-loop-vectorize -ftree-vectorize -funroll-loops -fuse-ld=bfd -fuse-linker-plugin -malign-data=cacheline -feliminate-unused-debug-types -fipa-pta -flto=16 -fno-plt -mtls-dialect=gnu2 -Wl,-sort-common -Wno-error -Wp,-D_REENTRANT -pipe -ffat-lto-objects -fPIC -fno-exceptions -pthread -static-libstdc++ -static-libgcc"
#
export LDFLAGS="-O3 -march=native -mtune=native -fgraphite-identity -Wall -Wl,--as-needed -Wl,--build-id=sha1 -Wl,--enable-new-dtags -Wl,--hash-style=gnu -Wl,-O2 -Wl,-z,now -Wl,-z,relro -falign-functions=32 -flimit-function-alignment -fasynchronous-unwind-tables -fdevirtualize-at-ltrans -floop-nest-optimize -fno-math-errno -fno-semantic-interposition -fno-stack-protector -fno-trapping-math -ftree-loop-distribute-patterns -ftree-loop-vectorize -ftree-vectorize -funroll-loops -fuse-ld=bfd -fuse-linker-plugin -malign-data=cacheline -feliminate-unused-debug-types -fipa-pta -flto=16 -fno-plt -mtls-dialect=gnu2 -Wl,-sort-common -Wno-error -Wp,-D_REENTRANT -pipe -ffat-lto-objects -fPIC -fno-exceptions -pthread -static-libstdc++ -static-libgcc"
#
export AR=gcc-ar
export RANLIB=gcc-ranlib
export NM=gcc-nm
#
export MAKEFLAGS=%{?_smp_mflags}
#
%global _lto_cflags 1
#global _lto_cflags %{nil}
#
unset CCACHE_DISABLE
export PATH="/usr/lib64/ccache/bin:$PATH"
export CCACHE_NOHASHDIR=true
export CCACHE_CPP2=true
export CCACHE_SLOPPINESS=pch_defines,time_macros,locale,file_stat_matches,file_stat_matches_ctime,include_file_ctime,include_file_mtime,modules,system_headers,clang_index_store,file_macro
#export CCACHE_SLOPPINESS=modules,include_file_mtime,include_file_ctime,time_macros,pch_defines,file_stat_matches,clang_index_store,system_headers,locale
#export CCACHE_SLOPPINESS=pch_defines,time_macros,locale,clang_index_store,file_macro
export CCACHE_DIR=/var/tmp/ccache
export CCACHE_BASEDIR=/builddir/build/BUILD
#export CCACHE_LOGFILE=/var/tmp/ccache/cache.debug
#export CCACHE_DEBUG=true
#export CCACHE_NODIRECT=true
## altflags1 end
%configure_buildtcl --enable-shared --with-x --enable-threads --enable-64bit
make  %{?_smp_mflags}  V=1 VERBOSE=1
## ccache stats
ccache -s
## ccache stats


%install
export SOURCE_DATE_EPOCH=1610089201
rm -rf %{buildroot}
%buildtcl_configure_install

%files
%defattr(-,root,root,-)

%files dev
%defattr(-,root,root,-)
/usr/include/jpegtcl.h
/usr/include/jpegtclDecls.h
/usr/include/pngtcl.h
/usr/include/pngtclDecls.h
/usr/include/tifftcl.h
/usr/include/tifftclDecls.h
/usr/include/tkimg.h
/usr/include/tkimgDecls.h
/usr/include/zlibtcl.h
/usr/include/zlibtclDecls.h
/usr/lib/tcl8.6/Img1.4.13/pkgIndex.tcl
/usr/lib/tcl8.6/jpegtclConfig.sh
/usr/lib/tcl8.6/pngtclConfig.sh
/usr/lib/tcl8.6/tifftclConfig.sh
/usr/lib/tcl8.6/tkimgConfig.sh
/usr/lib/tcl8.6/zlibtclConfig.sh

%files lib
%defattr(-,root,root,-)
/usr/lib/tcl8.6/Img1.4.13/libjpegtcl9.4.0.so
/usr/lib/tcl8.6/Img1.4.13/libpngtcl1.6.37.so
/usr/lib/tcl8.6/Img1.4.13/libtifftcl4.1.0.so
/usr/lib/tcl8.6/Img1.4.13/libtkimg1.4.13.so
/usr/lib/tcl8.6/Img1.4.13/libtkimgbmp1.4.13.so
/usr/lib/tcl8.6/Img1.4.13/libtkimgdted1.4.13.so
/usr/lib/tcl8.6/Img1.4.13/libtkimgflir1.4.13.so
/usr/lib/tcl8.6/Img1.4.13/libtkimggif1.4.13.so
/usr/lib/tcl8.6/Img1.4.13/libtkimgico1.4.13.so
/usr/lib/tcl8.6/Img1.4.13/libtkimgjpeg1.4.13.so
/usr/lib/tcl8.6/Img1.4.13/libtkimgpcx1.4.13.so
/usr/lib/tcl8.6/Img1.4.13/libtkimgpixmap1.4.13.so
/usr/lib/tcl8.6/Img1.4.13/libtkimgpng1.4.13.so
/usr/lib/tcl8.6/Img1.4.13/libtkimgppm1.4.13.so
/usr/lib/tcl8.6/Img1.4.13/libtkimgps1.4.13.so
/usr/lib/tcl8.6/Img1.4.13/libtkimgraw1.4.13.so
/usr/lib/tcl8.6/Img1.4.13/libtkimgsgi1.4.13.so
/usr/lib/tcl8.6/Img1.4.13/libtkimgsun1.4.13.so
/usr/lib/tcl8.6/Img1.4.13/libtkimgtga1.4.13.so
/usr/lib/tcl8.6/Img1.4.13/libtkimgtiff1.4.13.so
/usr/lib/tcl8.6/Img1.4.13/libtkimgwindow1.4.13.so
/usr/lib/tcl8.6/Img1.4.13/libtkimgxbm1.4.13.so
/usr/lib/tcl8.6/Img1.4.13/libtkimgxpm1.4.13.so
/usr/lib/tcl8.6/Img1.4.13/libzlibtcl1.2.11.so

%files man
%defattr(0644,root,root,0755)
/usr/share/man/mann/img-bmp.n
/usr/share/man/mann/img-dted.n
/usr/share/man/mann/img-gif.n
/usr/share/man/mann/img-ico.n
/usr/share/man/mann/img-jpeg.n
/usr/share/man/mann/img-pcx.n
/usr/share/man/mann/img-pixmap.n
/usr/share/man/mann/img-png.n
/usr/share/man/mann/img-ppm.n
/usr/share/man/mann/img-ps.n
/usr/share/man/mann/img-raw.n
/usr/share/man/mann/img-sgi.n
/usr/share/man/mann/img-sun.n
/usr/share/man/mann/img-tga.n
/usr/share/man/mann/img-tiff.n
/usr/share/man/mann/img-window.n
/usr/share/man/mann/img-xbm.n
/usr/share/man/mann/img-xpm.n
/usr/share/man/mann/img.n

%files staticdev
%defattr(-,root,root,-)
/usr/lib/tcl8.6/Img1.4.13/libjpegtclstub9.4.0.a
/usr/lib/tcl8.6/Img1.4.13/libpngtclstub1.6.37.a
/usr/lib/tcl8.6/Img1.4.13/libtifftclstub4.1.0.a
/usr/lib/tcl8.6/Img1.4.13/libtkimgstub1.4.13.a
/usr/lib/tcl8.6/Img1.4.13/libzlibtclstub1.2.11.a
